version: '3.7'
services:
  redis:
    container_name: redis-compose
    image: redis:latest
    ports:
      - 6377:6379
    networks:
      - mynetwork
  postgres:
    container_name: postgres-compose
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=greenanimalsbank
      - POSTGRES_PASSWORD=pass
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=greenanimalsbank-learn
    networks:
      - mynetwork
  app-golang:
    container_name: golang-compose
    image: app-golang:0.5
    ports:
      - 8007:8080
    depends_on:
      - redis
      - postgres
    environment:
      - REDIS_HOST=redis-compose
      - REDIS_PORT=6379
      - POSTGRES_HOST=postgres-compose
      - POSTGRES_PORT=5432
      - POSTGRES_USER=greenanimalsbank
      - POSTGRES_PASS=pass
      - POSTGRES_DB_NAME=greenanimalsbank-learn
      #- REDIS_PORT=6377
    #command: ["./wait-for-postgres.sh", "postgres-compose", "user", "pass"]
    networks:
      - mynetwork
networks: 
  mynetwork:
    name: mynetwork